
version: '3'

services:

  source:
    image: nginx:latest
    command: nginx-debug -g 'daemon off;'
    ports:
      - 8080:80
    volumes:
      - .:/usr/share/nginx/html:ro

  cache:
    image: seanhoughton/nginx-cache:test
    ports:
      - 8081:80
    environment:
      LISTENPORT: 80
      VERBOSE: 1
      UPSTREAM: ct-host-u118.ct.activision.com:3335;ct-host-u119.ct.activision.com:3335
      UPSTREAM_OPTS: max_fails=3 fail_timeout=30s
      UPSTREAM_PROTOCOL: http
      CACHE_SIZE: 100M
      WORKERS: 10
      MAX_EVENTS: 1000
      USE_PERFLOG: 0
      SSL: 'off'

  exporter:
      image: sophos/nginx-vts-exporter:latest
      ports:
        - 9913:9913
      environment:
        NGINX_STATUS: "http://cache/status/format/json"
